### PR TITLE
[REG-987] give validation examples their own bots

### PR DESCRIPTION
**Pull request by abeizer**
I figured it'd be easier to test validation bots alongside playtest bots if the validation bots had their own proper `index.js` files.

### CODE REVIEW

**Review by RG-nAmKcAz — APPROVED** [review]
Do we have an easy way to get this bots as a user ?

**Comment by abeizer** [comment]
> Do we have an easy way to get this bots as a user ?

We'd need to add these bots to the db with rgunitydev as their author. For my local table I copied a row for one of the other Unity bots and changed the path. We can create a migration for this... although I'm not a fan of using those for seeding test data

**Comment by RG-nAmKcAz** [comment]
> > Do we have an easy way to get this bots as a user ?
> 
> We'd need to add these bots to the db with rgunitydev as their author. For my local table I copied a row for one of the other Unity bots and changed the path. We can create a migration for this... although I'm not a fan of using those for seeding test data

Me either.  Check out RGService/unity-dev/setupUserAndBot.sql... Not a perfect solution, but outside the bounds of the migration of the DB.

**Comment by abeizer** [comment]
> > > Do we have an easy way to get this bots as a user ?
> > 
> > 
> > We'd need to add these bots to the db with rgunitydev as their author. For my local table I copied a row for one of the other Unity bots and changed the path. We can create a migration for this... although I'm not a fan of using those for seeding test data
> 
> Me either. Check out RGService/unity-dev/setupUserAndBot.sql... Not a perfect solution, but outside the bounds of the migration of the DB.

:-O Completely forgot about this. Updated [my other PR](https://github.com/Regression-Games/RegressionGames/pull/340)

**Review by vontell — APPROVED** [review]

**Pull request merged**
